name: FoodDiary Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright-tests:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd playwright
          npm install @playwright/test@1.38.0
      
      - name: Install Playwright browsers and system dependencies
        run: |
          cd playwright
          npx playwright install chromium
          npx playwright install-deps chromium
      
      - name: Run Playwright tests
        run: |
          cd playwright
          npx playwright test --reporter=html

      - name: List files
        if: always()
        run: |
          ls -la playwright/
          ls -la playwright/playwright-report/ || echo "playwright-report folder not found"
      
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright/playwright-report
